# Generated by Django 2.1.7 on 2019-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='pass_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
