# Generated by Django 2.1.7 on 2019-03-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('pass_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='playground.Student')),
            ],
            options={
                'verbose_name': 'StudentInfo',
                'verbose_name_plural': 'StudentInfos',
            },
        ),
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
