# Generated by Django 2.1.7 on 2019-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20190317_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
