# Generated by Django 2.1.7 on 2019-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20190317_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], default='J', max_length=1),
            preserve_default=False,
        ),
    ]
