# Generated by Django 2.1.7 on 2019-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior dev'), ('M', 'Middle feeder'), ('S', 'Senior pomidor')], max_length=1),
        ),
    ]
